"""adapters package — concrete implementations of port interfaces."""

from app.adapters.database import close_engine, get_engine, get_session_maker
from app.adapters.redis_client import (
    blacklist_key,
    blacklist_token,
    close_redis_client,
    get_redis_client,
    is_last_active_expired,
    is_refresh_token_valid,
    is_token_blacklisted,
    last_active_key,
    rate_limit_check,
    rate_limit_key,
    redis_delete,
    redis_exists,
    redis_expire,
    redis_get,
    redis_set,
    redis_setex,
    refresh_key,
    revoke_all_user_refresh_tokens,
    revoke_refresh_token,
    store_refresh_token,
    touch_last_active,
)

__all__ = [
    "close_engine",
    "close_redis_client",
    "get_engine",
    "get_redis_client",
    "get_session_maker",
    "blacklist_key",
    "blacklist_token",
    "is_last_active_expired",
    "is_refresh_token_valid",
    "is_token_blacklisted",
    "last_active_key",
    "rate_limit_check",
    "rate_limit_key",
    "redis_delete",
    "redis_exists",
    "redis_expire",
    "redis_get",
    "redis_set",
    "redis_setex",
    "refresh_key",
    "revoke_all_user_refresh_tokens",
    "revoke_refresh_token",
    "store_refresh_token",
    "touch_last_active",
]
